; PlatformIO — EPD 3D G6  |  Actuator 1 cycle test
; Target: ESP32-C6 SuperMini

[env:esp32c6_act_cycle]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board     = esp32-c6-devkitc-1
framework = arduino

board_build.flash_mode = qio
monitor_speed          = 115200
upload_speed           = 921600

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9

upload_port = COM28
