; PlatformIO — EPD 3D G6  |  OLED screen test
; 128x64 SSD1306 via I2C — SCL=GPIO6, SDA=GPIO7

[env:esp32c6_oled_test]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board     = esp32-c6-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed  = 921600
upload_port   = COM28

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9
